src=open('/home/claude/gen/gen_admin.py',encoding='utf-8').read().split("for k,v in out.items()")[0]
exec(src)
out={}
def av(t,c='#E3DDFF',s=36): return f'<span class="h" style="width:{s}px;height:{s}px;flex-shrink:0;border-radius:50%;border:2px solid {INK};background:{c};display:inline-flex;align-items:center;justify-content:center;font-size:{s*0.45:.0f}px;color:{INK};">{t}</span>'
# 1. join requests
rq=[('אבי שמעוני','050-2345678','משפחה עם 3 ילדים, גרים ברחוב הרצל 14','לפני שעתיים','#FFD9E8'),('דנה ברק','052-7766554','חברה בבית הכנסת הישן, עברנו לשכונה','אתמול','#CFF0FC'),('רועי אזולאי','054-1122334','בלי הערה','אתמול','#D7F5E8'),('מיכל פרידמן','050-8899001','מכירה את הגבאי יוסף','לפני 3 ימים','#E3DDFF')]
cols=[('מבקש/ת','width:200px;'),('הערה מהמבקש','flex:1;min-width:0;'),('מתי','width:90px;'),('פעולה','width:170px;')]
body=th(cols)
for i,(n,p,nt,w,c) in enumerate(rq):
    body+=tr([(f'<div style="display:flex;gap:10px;align-items:center;">{av(n[0],c)}<div style="display:flex;flex-direction:column;"><b>{n}</b><bdi style="color:{SOFT};font-size:12.5px;">{p}</bdi></div></div>',cols[0][1]),(nt,cols[1][1]),(w,cols[2][1]),(f'<span style="display:flex;gap:8px;">{btn("אישור",True)}{btn("דחייה")}</span>',cols[3][1])],i==len(rq)-1)
lst=panel(f'<div style="display:flex;align-items:center;gap:10px;">{h2("בקשות הצטרפות","4 ממתינות")}<span style="flex:1;"></span>{pill("ממתינות",Y)}{pill("אושרו","#fff")}{pill("נדחו","#fff")}</div>'+body,pad=16,gap=8,extra='flex:1;min-width:0;align-self:flex-start;')
side=panel(h2('מה קורה באישור')+tr([('המבקש/ת מקבל/ת הודעה ומופיע/ה בכרטיס החברות',''),('','')])+tr([('בוחרים מסלול ותוויות בעת האישור',''),('','')])+tr([('אפשר לאשר כמה בקשות יחד',''),('','')],True)+note('דחייה נשלחת בנוסח נעים, ואפשר להוסיף סיבה. המבקש/ת לא רואה פרטי חברים אחרים לעולם.'),pad=16,gap=4,extra='width:320px;flex-shrink:0;align-self:flex-start;')
out['D-AdmRequests']=shell('ד · בקשות הצטרפות','חברים',head('בקשות הצטרפות','',btn('אישור הכל',True))+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{lst}{side}</section>')
# 2. member profile page
def kv(k,v): return f'<div style="display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1.5px solid {LINE};"><span style="color:{SOFT};font-weight:700;">{k}</span><span style="font-weight:800;">{v}</span></div>'
hdr=f'<div style="background:{ORG};color:#fff;border-radius:18px;border:2.5px solid {INK};padding:16px;display:flex;align-items:center;gap:14px;">{av("ד","#fff",60)}<div style="flex:1;display:flex;flex-direction:column;"><span class="h" style="font-size:24px;">דוד כהן</span><span style="font-weight:700;opacity:.9;">משפחת כהן · ראש משק בית · חבר מאז 2019</span></div><span style="display:flex;gap:8px;">{pill("חוב פתוח",Y)}{pill("מחלוקת על חיוב","#CFF0FC")}</span></div>'
left=panel(h2('פרטים','לפי מה שהחבר אישר לארגון')+kv('טלפון','050-1234567')+kv('מייל','david@example.com')+kv('כתובת','הרצל 12, רעננה')+kv('בני משפחה','5 (שניים משלמים)')+kv('תאריך עברי','כ״ג תשרי')+'<div style="display:flex;gap:6px;flex-wrap:wrap;padding-top:6px;">'+stamp('מייסד','#5EE0C0',-3)+stamp('גבאי','#B9A4FF',3)+'</div>',pad=16,gap=2,extra='width:320px;flex-shrink:0;align-self:flex-start;')
cols=[('תאריך','width:60px;'),('חיוב','flex:1;white-space:nowrap;'),('סכום','width:70px;text-align:end;'),('סטטוס','width:80px;')]
rws=[('01.10','דמי ועד · אוקטובר','₪600','פתוח','#FFE9E6'),('01.09','דמי ועד · ספטמבר','₪600','שולם','#D7F5E8'),('01.08','דמי ועד · אוגוסט','₪600','שולם','#D7F5E8'),('12.07','תרומה · עלייה לתורה','₪360','שולם','#D7F5E8')]
ch=panel(f'<div style="display:flex;align-items:center;">{h2("חיובים ותשלומים")}<span style="flex:1;"></span>{btn("רישום תשלום ידני")}{btn("חיוב חדש",True)}</div>'+th(cols)+''.join(tr([(d,cols[0][1]),(t,cols[1][1]),(f'<bdi><b>{a}</b></bdi>',cols[2][1]),(pill(s,bg),cols[3][1])],i==len(rws)-1) for i,(d,t,a,s,bg) in enumerate(rws)),pad=16,gap=6,extra='flex:1;min-width:0;')
act=panel(h2('פעולות')+btn('שליחת תזכורת',True)+btn('הודעה אישית')+btn('מחלוקת על חיוב')+btn('שינוי מסלול')+btn('הקפאת מנוי')+btn('הסרת חבר',danger=True)+note('הסרת חבר עם חוב פתוח שומרת את החוב (Q-L1).'),pad=16,gap=8,extra='width:230px;flex-shrink:0;align-self:flex-start;')
out['D-AdmMember']=shell('ד · תיק חבר','חברים',head('תיק חבר','')+hdr+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{left}{ch}{act}</section>')
# 3. reports
bars=''.join(f'<div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;gap:4px;"><span style="font-size:11.5px;font-weight:800;">{v}</span><span style="width:100%;height:{h}px;background:{ORG};border:2px solid {INK};border-radius:8px 8px 0 0;"></span><span style="font-size:12px;font-weight:700;color:{SOFT};">{m}</span></div>' for m,v,h in [('מאי','14K',90),('יוני','16K',104),('יולי','12K',78),('אוג׳','17K',110),('ספט׳','19K',124),('אוק׳','18K',118)])
c1=panel(h2('גבייה לפי חודש','נגבה בפועל, ב-₪')+f'<div style="display:flex;gap:10px;align-items:flex-end;height:170px;padding-top:6px;">{bars}</div>',pad=16,extra='flex:1.3;')
def stat(v,l,c): return f'<div style="flex:1;padding:12px;border:2px solid {INK};border-radius:14px;border-top:6px solid {c};background:#fff;display:flex;flex-direction:column;"><bdi class="h" style="font-size:26px;">{v}</bdi><span style="font-weight:700;color:{SOFT};font-size:13px;">{l}</span></div>'
c2=panel(h2('מצב חובות')+f'<div style="display:flex;gap:10px;">{stat("34","חברים בחוב",DANGER)}{stat("₪7,900","סך החוב",Y)}{stat("68%","שיעור גבייה",GREEN)}</div>'+note('חברים בהוראת קבע משלמים בזמן פי 3 יותר. שווה לעודד מעבר.'),pad=16,extra='flex:1;')
rep=[('דוח גבייה חודשי','לפי חיוב, סטטוס ואמצעי תשלום'),('חובות פתוחים','לפי חבר, גיל חוב ותזכורות'),('רשימת חברים','לפי מסלול ותווית'),('תנועות קופה','לתאום מול הנהלת חשבונות'),('קבלות','כל הקבלות שהופקו בתקופה')]
c3=panel(h2('ייצוא דוחות','CSV או PDF')+''.join(tr([(f'<b>{t}</b><br><span style="color:{SOFT};font-size:12.5px;">{s}</span>','flex:1;'),(btn('ייצוא'),'')],i==len(rep)-1) for i,(t,s) in enumerate(rep)),pad=16,gap=2,extra='flex:1;')
out['D-AdmReports']=shell('ד · דוחות','דוחות',head('דוחות','6 חודשים אחרונים',pill('מאי עד אוק׳ 2026',Y))+f'<section style="display:flex;gap:14px;">{c1}{c2}</section><section style="flex:1;min-height:0;display:flex;">{c3}</section>')
# 4. message to members
form=panel(h2('הודעה חדשה')+fld('נמענים','כל החברים הפעילים · 312','')+f'<div style="display:flex;gap:8px;">{pill("כולם",Y)}{pill("לפי תווית","#fff")}{pill("בחוב","#fff")}{pill("נבחרים","#fff")}</div>'+fld('כותרת','שינוי בשעות התפילה בחגים')+fld('תוכן ההודעה','שלום לכולם, בשבוע הבא יחולו שינויים בשעות התפילה. הפרטים המלאים בלוח המודעות.','',h=120)+f'<div style="display:flex;flex-direction:column;gap:8px;"><span style="font-weight:800;">איך לשלוח</span><div style="display:flex;gap:16px;">{chk(True,"התראת דחיפה")}{chk(False,"SMS")}{chk(True,"דוא״ל")}</div></div>'+note('חברים שכיבו הודעות כלליות לא יקבלו. הודעות על חובות ותשלומים מגיעות תמיד.'),pad=20,gap=14,extra='flex:1;')
def push():
    return f'<div style="border:2.5px solid {INK};border-radius:18px;background:#fff;box-shadow:0 3px 0 {INK};padding:12px 14px;display:flex;gap:10px;align-items:center;"><span class="h" style="width:40px;height:40px;border-radius:50%;background:{ORG};color:#fff;border:2px solid {INK};display:inline-flex;align-items:center;justify-content:center;font-size:19px;">א</span><div style="display:flex;flex-direction:column;"><b>אור חדש</b><span style="font-weight:700;">שינוי בשעות התפילה בחגים</span><span style="color:{SOFT};font-size:13px;">שלום לכולם, בשבוע הבא יחולו שינויים…</span></div></div>'
pv=panel(h2('כך החבר יראה')+push()+tr([('נשלח אל',''),('<b>289 חברים</b>','')])+tr([('לא יקבלו (כיבו הודעות)',''),('<b>23</b>','')],True),pad=16,gap=8,extra='width:420px;flex-shrink:0;align-self:flex-start;')
out['D-AdmMessage']=shell('ד · הודעה לחברים','הודעות',head('הודעה לחברים','',btn('שמירה כטיוטה')+btn('שליחה',True))+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{form}{pv}</section>')
# 5. public page editor
pe=panel(h2('עמוד הארגון הציבורי','מה שאנשים רואים לפני שהם מצטרפים')+fld('שם','אור חדש')+fld('משפט הזמנה','בית כנסת קהילתי בלב השכונה.')+fld('תיאור','תפילות כל יום, שיעורים, ארוחות קהילתיות. מתאים למשפחות ולבודדים.','',h=80)+f'<div style="display:flex;flex-direction:column;gap:8px;"><span style="font-weight:800;">מסלולים שיוצגו</span>'+tr([('מנוי שנתי · ₪2,200',''),(tg(True),'')])+tr([('מנוי חודשי · ₪220',''),(tg(True),'')])+tr([('סטודנטים · ₪90',''),(tg(False),'')],True)+'</div>'+f'<div style="display:flex;gap:16px;">{chk(True,"תוויות ציבוריות")}{chk(True,"שעות פעילות")}{chk(False,"מספר חברים")}</div>',pad=20,gap=12,extra='flex:1;')
org=f'<div style="border:2.5px solid {INK};border-radius:20px;overflow:hidden;background:#fff;box-shadow:0 3px 0 {INK};"><div style="background:{ORG};color:#fff;padding:16px;display:flex;gap:12px;align-items:center;">{av("א","#fff",52)}<div style="display:flex;flex-direction:column;"><span class="h" style="font-size:22px;">אור חדש</span><span style="font-weight:700;opacity:.9;">בית כנסת קהילתי בלב השכונה.</span></div></div><div style="padding:14px;display:flex;flex-direction:column;gap:8px;font-weight:600;"><span>תפילות כל יום, שיעורים, ארוחות קהילתיות. מתאים למשפחות ולבודדים.</span><div style="display:flex;justify-content:space-between;"><b>מנוי שנתי</b><bdi><b>₪2,200</b></bdi></div><div style="display:flex;justify-content:space-between;"><b>מנוי חודשי</b><bdi><b>₪220</b></bdi></div><span style="height:44px;border-radius:22px;border:2px solid {INK};background:{Y};display:flex;align-items:center;justify-content:center;font-weight:800;">בקשה להצטרפות</span></div></div>'
out['D-AdmPublicPage']=shell('ד · עמוד ציבורי','הגדרות הארגון',head('עמוד ציבורי','תצוגה מקדימה כפי שמופיעה לחברים עתידיים',btn('ביטול')+btn('פרסום',True))+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{pe}<div style="width:430px;flex-shrink:0;display:flex;flex-direction:column;gap:14px;">{panel(h2("תצוגה מקדימה")+org,pad=16)}</div></section>')
for k,v in out.items(): open(f'/home/claude/project/{k}.dc.html','w',encoding='utf-8').write(v)
print(list(out))
