# Org-creation wizard steps 1, 2, 5 (steps 3, 4 live in gen_admin.py).
src=open('/home/claude/gen/gen_admin.py',encoding='utf-8').read().split("for k,v in out.items()")[0]
exec(src)
out5={}
def dots(cols,sel):
    return ''.join(f'<span style="width:44px;height:44px;border-radius:50%;background:{c};border:2.5px solid {INK};{"box-shadow:0 0 0 3px #fff,0 0 0 5px "+INK+";" if i==sel else ""}"></span>' for i,c in enumerate(cols))
COLS=['#5B3DF5','#FF5A36','#00B67A','#FF5C9E','#18B8F0','#1E1633']
# step 1: details
w1=panel(h2('נתחיל מהשם','זה מה שהחברים יראו בראש הכרטיס שלהם')+fld('שם הארגון','אור חדש')+f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">{fld("עיר","מודיעין")}{fld("מדינה","ישראל")}</div>'
 +f'<div style="display:flex;flex-direction:column;gap:8px;"><b>צבע הארגון</b><div style="display:flex;gap:12px;">{dots(COLS,0)}</div><span style="font-size:13px;color:{SOFT};font-weight:600;">בוחרים אחד, והמערכת דואגת שהכול יישאר קריא.</span></div>'
 +fld('לוגו','',"אפשר גם אחר כך. מרובע, לפחות 256 פיקסלים",opt=True,ph=True)
 +f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">{fld("שפת הארגון","עברית")}{fld("מטבע","שקל (₪)")}</div>',pad=20,gap=12,extra='flex:1;')
pv1=panel(h2('כך הכרטיס ייראה')+f'<div style="border:2.5px solid {INK};border-radius:18px;overflow:hidden;background:#FFF9EC;box-shadow:0 3px 0 {INK};"><div style="background:{ORG};color:#fff;padding:14px;display:flex;gap:10px;align-items:center;"><span class="h" style="width:44px;height:44px;flex-shrink:0;border-radius:50%;border:2px solid {INK};background:#fff;display:inline-flex;align-items:center;justify-content:center;font-size:20px;color:{INK};">א</span><div style="display:flex;flex-direction:column;"><span class="h" style="font-size:20px;">אור חדש</span><span style="font-size:12.5px;font-weight:700;">מודיעין</span></div></div><div style="padding:12px 14px;font-weight:700;color:{SOFT};">החברים שלכם יראו כך את הארגון בארנק.</div></div>'+note('שם, עיר וצבע אפשר לשנות בכל רגע בהגדרות.'),pad=16,gap=12,extra='width:430px;flex-shrink:0;align-self:flex-start;')
out5['D-AdmWizard1']=shell('ד · הקמת ארגון · פרטי הארגון','הגדרות הארגון',head('הקמת הארגון','שלב 1 מתוך 5')+stepper(1)+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{w1}{pv1}</section>'+f'<div style="display:flex;gap:12px;flex-shrink:0;align-items:center;"><span style="flex:1;"></span><span style="font-weight:700;color:{SOFT};">נשמר אוטומטית</span>{btn("המשך",True)}</div>')
# step 2: type
def typ(n,sub,on):
    return f'<div style="flex:1;min-width:0;display:flex;flex-direction:column;gap:6px;padding:12px;border:2.5px solid {INK};border-radius:16px;background:{"#FFF6D1" if on else "#fff"};{"box-shadow:0 3px 0 "+INK+";" if on else ""}"><span style="display:flex;align-items:center;gap:8px;font-weight:800;font-size:17px;">{radio(on)}{n}</span><span style="font-size:13px;font-weight:600;color:{SOFT};line-height:1.4;">{sub}</span></div>'
tp=panel(h2('איזה ארגון זה?','מתאים לכם את המילים והמודולים. הליבה זהה לכולם')+f'<div style="display:flex;gap:10px;">{typ("בית כנסת","תפילות, תרומות, יארצייט",True)}{typ("ועד בית","דמי ועד, תקלות, אסיפות",False)}{typ("חדר כושר","כניסות, שיעורים, הקפאות",False)}</div><div style="display:flex;gap:10px;">{typ("מועדון","רמות חברות, אירועים, הטבות",False)}{typ("משהו אחר","ליבה בלבד: חברים, כספים, הודעות",False)}<span style="flex:1;"></span></div>'
 +f'<div style="display:flex;flex-direction:column;gap:8px;"><b>כמה חברים בערך?</b><div style="display:flex;gap:8px;">{pill("<bdi>עד 50</bdi>","#fff")}{pill("<bdi>50–150</bdi>",Y)}{pill("<bdi>150–500</bdi>","#fff")}{pill("<bdi>500+</bdi>","#fff")}</div></div>'
 +opt('יש לנו רשימת חברים קיימת','תוכלו לייבא אותה מקובץ אחרי ההקמה. נעזור להתאים עמודות.',True)+opt('מתחילים מאפס','מוסיפים חברים אחד אחד, או מזמינים אותם להצטרף בעצמם.',False),pad=20,gap=12,extra='flex:1;')
tpv=panel(h2('מה מקבלים בבית כנסת')+f'<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1.5px solid {LINE};"><span style="color:{SOFT};font-weight:700;">חבר נקרא</span><b>מתפלל</b></div><div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1.5px solid {LINE};"><span style="color:{SOFT};font-weight:700;">מנהל נקרא</span><b>גבאי</b></div><span style="font-weight:800;">מודולים שנפתחים</span><div style="display:flex;flex-direction:column;gap:6px;">'+''.join(f'<span style="min-height:34px;box-sizing:border-box;padding:0 10px;border:2px dashed {INK};border-radius:10px;background:#E3DDFF;font-weight:800;display:flex;align-items:center;">{l}</span>' for l,_ in PACKS["synagogue"][1])+'</div>'+note('אפשר להחליף סוג או לכבות מודולים אחר כך, בלי לאבד נתונים.'),pad=16,gap=10,extra='width:430px;flex-shrink:0;align-self:flex-start;')
out5['D-AdmWizard2']=shell('ד · הקמת ארגון · סוג וחברים','הגדרות הארגון',head('הקמת הארגון','שלב 2 מתוך 5')+stepper(2)+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{tp}{tpv}</section>'+f'<div style="display:flex;gap:12px;flex-shrink:0;align-items:center;">{btn("חזרה")}<span style="flex:1;"></span><span style="font-weight:700;color:{SOFT};">נשמר אוטומטית</span>{btn("המשך",True)}</div>')
# step 5: invite + done
iv=panel(h2('מי מצטרף ראשון?','כל הצטרפות היא דו-צדדית: מזמינים, והאדם מאשר')+opt('קישור הזמנה','שולחים בוואטסאפ או במייל. כל מי שנכנס מבקש להצטרף, ואתם מאשרים.',True,'הכי קל')+f'<div style="display:flex;gap:8px;align-items:center;padding:10px 12px;border:2px solid {INK};border-radius:14px;background:#fff;"><span style="flex:1;direction:ltr;text-align:start;font-weight:700;">app.example/join/or-hadash</span>{btn("העתקה")}</div>'+opt('הזמנה לפי טלפון','מדביקים רשימת מספרים, ונשלח לכל אחד הזמנה אישית.',False)+opt('ייבוא מקובץ','CSV או אקסל. נתאים עמודות ונראה תצוגה מקדימה לפני שמזמינים.',False),pad=20,gap=12,extra='flex:1;')
dn=panel(h2('מה הוקם עד עכשיו')+''.join(f'<div style="display:flex;gap:10px;align-items:center;padding:7px 0;border-bottom:1.5px solid {LINE};"><span style="width:26px;height:26px;border-radius:50%;background:{GREEN};border:2px solid {INK};display:inline-flex;align-items:center;justify-content:center;flex-shrink:0;color:{INK};">{ico("M5 12.5l4.5 4.5L19 7.5",14,3.2)}</span><b>{t}</b></div>' for t in ['שם, עיר וצבע','סוג ארגון: בית כנסת','גבייה דרך המערכת','חשבון לקבלת כסף: בבדיקה'])+note('אפשר לסיים עכשיו ולהזמין אחר כך. הכול ממשיך מהמסך "סקירה".'),pad=16,gap=6,extra='width:430px;flex-shrink:0;align-self:flex-start;')
out5['D-AdmWizard5']=shell('ד · הקמת ארגון · הזמנת חברים','הגדרות הארגון',head('הקמת הארגון','שלב 5 מתוך 5')+stepper(5)+f'<section style="flex:1;min-height:0;display:flex;gap:14px;">{iv}{dn}</section>'+f'<div style="display:flex;gap:12px;flex-shrink:0;align-items:center;">{btn("חזרה")}<span style="flex:1;"></span>{btn("דלגו, אזמין אחר כך")}{btn("סיום ופתיחת הארגון",True)}</div>')
for k,v in out5.items(): open(f'/home/claude/project/{k}.dc.html','w',encoding='utf-8').write(v)
print(list(out5))
